### ISSUE TITLE
password recovery email

### ISSUE THREAD

**Issue by mrkistler** [SICASFoundation/smir-dev-board#11]
we cannot change the login email. some users dont have access to their registration email anymore. we need to have a recovery email (default use the registration email) to give them the option to send the recovery password to a different email address

**Comment by niklr** [comment]
if you are logged in we should provide the option to change the email address. however, sending the recovery link to reset the password to another email address will not be implemented due to security reasons. or do you mean something else?

**Comment by mrkistler** [comment]
i dont see the security issue. other services are doing exactly this. (google eg)
