### ISSUE TITLE
Redirect to demo.smir.ch instead of demo.virtualskeleton.ch

### ISSUE THREAD

**Issue by niklr** [SICASFoundation/smir-dev-board#19]

**Comment by niklr** [comment]
Kannst du ein "Let's Encrypt" Wildcard Zertifikat für *.smir.ch Subdomains einrichten?

**Comment by mrkistler** [comment]
Will Let’s Encrypt issue wildcard certificates?

We currently have no plans to do so, but it is a possibility in the future. Hopefully wildcards aren’t necessary for the vast majority of our potential subscribers because it should be easy to get and manage certificates for all subdomains.
