### ISSUE TITLE
virtual groups api

### ISSUE THREAD

**Issue by mrkistler** [SICASFoundation/smir-dev-board#63]
virtual groups are not supported through the api. please add

eg id 266 is a virtual group.

**Comment by niklr** [comment]
- separate API endpoint? /api/virtual_groups
- list users (id, username) inside virtual groups?
- hide users for World and Registered virtual groups?
- API endpoint to handle group-user relation: /api/group-users

**Comment by niklr** [comment]
- introduce types in /api/groups endpoint
- hide users for all groups for now
