### ISSUE TITLE
registration fails for long firstname

### ISSUE THREAD

**Issue by mrkistler** [SICASFoundation/smir-dev-board#70]
Allow longer input or/and display better error message and cut input at max chars in the input field

<input maxlength="32" ..../>

1. User could not register, receives this message
Error Message: Error failed. please try again later or contact admin
2. Log shows:
Log: String or binary data would be truncated

Input: 
- Firstname: 18 char (incl whitespace)
- Lastname: 10 char

**Comment by niklr** [comment]
- Firstname: 16 chars
- Lastname: 32 chars
