### ISSUE TITLE
implement visceral script for isles 

### ISSUE THREAD

**Issue by mrkistler** [SICASFoundation/smir-dev-board#8]
as discussed:

https://github.com/Visceral-Project/EvaluateSegmentation

im anhang ein output mit allen werten. lässt sich easy auf die
gewünschten werte reduzieren:

ASSD: average symmertric surface distance kann ich noch nicht zuordnen, -> wohl AVGDIST: calculate Average Distance in voxels
Hausdorff Distance: HDRFDST calculate Hausdorff Distance
Dice: DICE: calculate Dice Coefficient
Precision: PRCISON: calculate Precision
Recall: SNSVTY: calculate Sensitivity (Recall, true positive rate)

`EvaluateSegmentation gt seg -xml xmlfile -use
AVGDIST,HDRFDST,DICE,PRCISON,SNSVTY -nostreaming`

**Comment by niklr** [comment]
Neue Resultate mit ASSD 0 und zusätzlicher Metrik AVGDIST abspeichern.

**Comment by niklr** [comment]
ISLES 2017 start page

**Comment by niklr** [comment]
-unit millimeter
